server:
  port: 8081

kafka-topics:
  stock-prices: "stock.prices"
  stock-signals: "stock.signals"

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.example.kafka.config.StockPriceSerializer

  application:
    name: kafka

