server:
  port: 8081

kafka-topics:
  stock-prices: "stock.prices"
  stock-signals: "stock.signals"

spring:
  kafka:
    producers:
      stock-prices:
        bootstrap-servers: localhost:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.example.kafka.config.StockPriceSerializer
      stock-signals:
        bootstrap-servers: localhost:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.example.kafka.config.StockSignalSerializer


  application:
    name: kafka

