server:
  port: 8080

kafka-topics:
  stock-prices: "stock.prices"
  invalid-stock-prices: "invalid.stock.prices"

spring:
  application:
    name: reacting_spring
  rsocket:
    server:
      transport: websocket
      mapping-path: /rsocket
      port: 8082

  kafka:
    bootstrap-servers: localhost:9092
    streams:
      properties:
        application-id: stock-price-streams
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.example.config.StockPriceSerde